baseURL = "http://example.org/"
languageCode = "en-us"
title = "Anchore Enterprise Documentation"
theme = "hugo-theme-learn"

[params]
themeVariant = "blue"
enableGitInfo = "true"
googleAnalytics = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]
